name 'checkmks'
source_url       'https://github.com/emo3/checkmks'
issues_url       'https://github.com/emo3/checkmks/issues'
maintainer       'Ed Overton'
maintainer_email 'you1@example.com'
chef_version     '>= 15.0'
license          'Apache-2.0'
description      'Installs/Configures checkmk server'
version          '1.12.0'

supports 'redhat'
supports 'centos'
supports 'almalinux'

depends 'line'
