default['cmk']['media_url'] = 'http://10.1.1.30/media'
default['cmk']['server_rpm'] = 'check-mk-raw-1.5.0p21-el7-38.x86_64.rpm'
default['cmk']['instance_name'] = 'sandbox'
default['cmk']['admin_passwd'] = 'cmkadmin'
default['cmk']['server_ip'] = '10.1.1.101'
